# Show the time spent with the job on the output.
$show_time = 1;

# The one selected here is the default. You can override with, e.g.,
# "latexmk --xelatex".
$pdf_mode = 1; # PDF directly with pdfLaTeX.
# $pdf_mode = 4; # PDF directly with LuaLaTeX.
# $pdf_mode = 5; # PDF directly with XeLaTeX.
$dvi_mode = $postscript_mode = 0;

# We are using Minted, which runs a custom third-party tool, and needs the
# '--shell-escape' flag.
#
# (via http://tex.stackexchange.com/a/374161)
$lualatex = "lualatex --halt-on-error --shell-escape %O %S";
$pdflatex = "pdflatex --halt-on-error --shell-escape %O %S";
$xelatex  = "xelatex  --halt-on-error --shell-escape %O %S";

# Clear SyncTeX.
push @generated_exts, "synctex.gz", "synctex(busy)";
$clean_ext .= " synctex.gz synctex(busy)";

# By default, latexmk treats .bbl files as non-regeneratable.
# This is because the .bib from which they are made is not always available.
# See the documentation for a fuller explanation, especially the explanation
# of the $bibtex_use variable.
#
# To get latexmk -C to delete .bbl files, put the following in an
# initialization file.
#
# (via http://tex.stackexchange.com/a/83384)
$bibtex_use = 2;

# BibLaTeX loads logreq, which generates this file.
# (via http://tex.stackexchange.com/a/672841)
push @generated_exts, "run.xml";
$clean_ext .= " run.xml";

# Have LaTeXmk run the 'makeindex' tool so nomenclatures are generated properly.
#
# (via http://tex.stackexchange.com/a/105978)
add_cus_dep( "nlo", "nls", 0, "makenlo2nls" );
sub makenlo2nls {
  system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
}
push @generated_exts, "nlo", "nls";
$clean_ext .= " nlo nls";

# We use minted and generate a "List of Listings" which should be autocleaned.
push @generated_exts, "lol";
$clean_ext .= " lol";

# Clear the "List of Algorithms" file generated by algorithm2e.
push @generated_exts, "loa";
$clean_ext .= " loa";

# We use the todonotes package, which generates another auxilliary file.
push @generated_exts, "tdo";
$clean_ext .= " tdo";

# Since at least latexmk version 4.80, we can delete the minted cache.
# (via http://tex.stackexchange.com/a/275220)
$clean_ext .= " _minted-%R/* _minted-%R";
